-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_CAR C
WHERE C.CAR_TYPE = '세단' AND TO_CHAR(H.START_DATE, 'YYYYMM') = '202210' AND C.CAR_ID = H.CAR_ID
ORDER BY 1 DESC;